/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50718
 Source Host           : localhost:3306
 Source Schema         : zaixian

 Target Server Type    : MySQL
 Target Server Version : 50718
 File Encoding         : 65001

 Date: 05/02/2018 20:03:29
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for questions
-- ----------------------------
DROP TABLE IF EXISTS `questions`;
CREATE TABLE `questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timu` varchar(200) NOT NULL,
  `optionA` varchar(200) NOT NULL,
  `optionB` varchar(200) NOT NULL,
  `optionC` varchar(200) NOT NULL,
  `answer` varchar(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=500 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of questions
-- ----------------------------
BEGIN;
INSERT INTO `questions` VALUES (1, '人体细胞中含量最高的是?', '水', '蛋白质', '脂肪', 'A');
INSERT INTO `questions` VALUES (2, '4的2次方除以3的余数为？ ', '2', '1', '0', 'B');
INSERT INTO `questions` VALUES (3, '元素周期表第38位元素的元素单质在常温常压下是什么物态？ ', '气态', '液态', '固态', 'C');
INSERT INTO `questions` VALUES (4, '歌曲《你是我的眼》的作曲者？', '陈飞午', '萧煌奇', '张雨生', 'B');
INSERT INTO `questions` VALUES (5, '电影《指环王》中的指环可以让人拥有什么技能？', '隐身', '分身', '飞', 'A');
INSERT INTO `questions` VALUES (6, '“心心相印，印贼做父，父相伤害”这是在调侃东北话和哪个省的口音？', '福建', '河南', '陕西', 'A');
INSERT INTO `questions` VALUES (7, '2005年，被排出出行星范围、划为矮行星的是？', '海王星', '冥王星', '天王星', 'B');
INSERT INTO `questions` VALUES (8, '“大白汽车分期”首付10%就可开走新车，一辆10万元的新车应该首付多少？ ', '1万', '10万', '100万', 'A');
INSERT INTO `questions` VALUES (9, '元素周期表中，没有以下哪个字母？ ', 'J', 'V', 'W', 'A');
INSERT INTO `questions` VALUES (10, '某数与-25的和是18的相反数，那么这个数是？', '7', '8', '9', 'A');
INSERT INTO `questions` VALUES (11, '以下哪款酒不属于“长岛冰茶”的基酒是？', '威士忌', '伏特加', '龙舌兰', 'A');
INSERT INTO `questions` VALUES (13, '下列哪个虚拟人物的技能是“天锁斩月”？', '月光之女——露娜', '永恒之月——芈月', '死神——黑崎一护', 'C');
INSERT INTO `questions` VALUES (14, '芬兰与朝鲜间相隔国家的总面积与以下哪个面积最接近？', '冥王星', '月球', '海王星', 'A');
INSERT INTO `questions` VALUES (15, '20W、160E组成的经线圈是？ ', '南北半球的分界线', '东西半球的分界线', '李诞的发际线', 'B');
INSERT INTO `questions` VALUES (16, 'AFI百年最伟大的女演员中“奥黛丽 赫本”排名第几？', '第一', '第二', '第三', 'C');
INSERT INTO `questions` VALUES (17, '下列全部属于九叶诗派的一组诗人是？', '绿原、阿垅、王馨迪', '穆旦、郑敏、袁可嘉', '唐祈、卞之琳、鲁藜', 'B');
INSERT INTO `questions` VALUES (18, '以下哪个时期男人头上的辫子粗细能穿过铜钱？', '清朝前期', '清朝中期', '清朝晚期', 'A');
INSERT INTO `questions` VALUES (19, '在日本，若果汁饮料包装上出现一只对半切开的橙子，证明果汁含量为？', '25%', '50%', '100%', 'C');
INSERT INTO `questions` VALUES (20, '以下哪部电影不是《盗梦空间》男主角参演过的作品？', '飞行者', '海滩', '心灵捕手', 'C');
INSERT INTO `questions` VALUES (21, '下列不属于《历代神仙演义》中的72变的是？', '穿越', '吞刀', '医药', 'A');
INSERT INTO `questions` VALUES (23, '假设某人的智商为109那么他跟一般人相比可以说是？', '智力低下', '智商超群', '智力平平', 'C');
INSERT INTO `questions` VALUES (24, '周杰伦《我的地盘》中，歌词“在我地盘这”重复了几次？', '9次', '12次', '15次', 'A');
INSERT INTO `questions` VALUES (25, '与我国陆地接壤的国家当中，国土面积排行第三位的是？', '蒙古', '印度', '哈萨克斯坦', 'C');
INSERT INTO `questions` VALUES (26, '以下哪两部电影的女主角是同一个人？', '《画皮》与《画壁》', '《革命之路》与《朗读者》', '《雏菊》与《晚秋》', 'B');
INSERT INTO `questions` VALUES (27, '以下哪个建筑的设计不是出自“望京soho”的设计师之手？', '广州大剧院', '南京青奥中心', '北京中央公园广场', 'C');
INSERT INTO `questions` VALUES (28, '直角三角形中，勾股定理是指三边的关系为？', 'a²+b²=c²', 'a²-b²=c²', 'a²*b²=c²', 'A');
INSERT INTO `questions` VALUES (29, '下列哪个不是美国宝洁公司的产品？', '舒肤佳香皂', '潘婷洗发水', '纳爱斯牙膏', 'C');
INSERT INTO `questions` VALUES (30, '《海贼王》是哪位漫画师的作品？', '尾田荣一郎', '青山刚昌', '新海诚', 'A');
INSERT INTO `questions` VALUES (31, '世界智力运动会竞技项目之一五子棋最高段位为？', '九段', '十二段', '十八段', 'A');
INSERT INTO `questions` VALUES (32, '青岛海鲜很有名，下列哪组海鲜都属于软体动物？', '章鱼、蛤蜊', '鲳鱼、牡蛎', '鲍鱼、海蛇', 'A');
INSERT INTO `questions` VALUES (33, '坦克是哪个国家发明的？', '德国', '英国', '俄罗斯', 'B');
INSERT INTO `questions` VALUES (34, '用椰子和西瓜打头哪一个比较痛？', '椰子', '西瓜', '头', 'C');
INSERT INTO `questions` VALUES (35, '“有约不来过夜半，闲敲棋子落灯花”中“灯花”是？', '燃尽的灯芯', '花灯的灯烛', '灯谜', 'A');
INSERT INTO `questions` VALUES (36, '电影《投名状》改编自清末四大奇案之一，请问是哪个奇案？', '杨乃武与小白菜', '张文祥刺马案', '太原奇案', 'B');
INSERT INTO `questions` VALUES (37, '美国军用飞机编号“F”的含义是指哪类型飞机？', '反潜机', '轰炸机', '战斗机', 'C');
INSERT INTO `questions` VALUES (38, '“食、色，性也。”意思是说，贪吃、好色是人类的本性，这是谁的观点？', '孔子', '告子', '孟子', 'B');
INSERT INTO `questions` VALUES (39, '别名“洗肠草”的是哪种蔬菜？', '香菜', '韭菜', '油麦菜', 'B');
INSERT INTO `questions` VALUES (40, '《西游记》中说：“我叫你一声，你敢答应吗？”的妖精是？', '金角大王', '银角大王', '铁角大王', 'B');
INSERT INTO `questions` VALUES (41, '电影《魂断蓝桥》是以哪座城市为背景？', '西雅图', '巴黎', '伦敦', 'C');
INSERT INTO `questions` VALUES (42, '中国最早的词典叫什么？', '《尔雅》', '《新华词典》', '《有道词典》', 'A');
INSERT INTO `questions` VALUES (43, '巴西的国旗没有的颜色是？', '红色', '黄色', '蓝色', 'A');
INSERT INTO `questions` VALUES (44, '一碗100g米饭的热量是多少大卡？', '112大卡', '116大卡', '120大卡', 'B');
INSERT INTO `questions` VALUES (45, '下列哪个字有迅速的含义？', '骉', '猋', '鱻', 'B');
INSERT INTO `questions` VALUES (46, '赵又廷因为出演了哪部电视剧而得到了外号“姑父”？', '琅琊榜', '三生三世十里桃花', '白夜追凶', 'B');
INSERT INTO `questions` VALUES (47, '电视剧《情深深雨蒙蒙》中书桓当年离开依萍去的绥远，是现今的哪里？', '呼和浩特', '太原', '无锡', 'A');
INSERT INTO `questions` VALUES (48, '日常生活中经常可以依据动物的某些行为预判天气，下列对应正确的是？', '蚂蚁垒窝—晴天', '麻雀囤食—雨天', '龟背冒汗—雨天', 'C');
INSERT INTO `questions` VALUES (49, '被称为非洲平头哥，人狠话不多的是哪种动物？', '蜜獾', '猪獾', '貘', 'A');
INSERT INTO `questions` VALUES (50, '“酒”与中华文化结下了不解之缘，酒能消愁，酒能增进友谊，李白说：', '何以解忧，唯有杜康', '呼儿将出换美酒，与尔同销万古愁', '今朝有酒今朝醉，明日愁来明日愁', 'B');
INSERT INTO `questions` VALUES (51, '例行检查时发现胚胎刚具人形，请帮其判断已怀孕的大约时间是？', '8周', '16周', '24周', 'A');
INSERT INTO `questions` VALUES (52, '鱼翅是哪种动物的鳍所制成的？', '鲨鱼', '鲸鱼', '小丑鱼', 'A');
INSERT INTO `questions` VALUES (53, '“冰淇淋”最早起源于哪个国家？', '意大利', '中国', '土耳其', 'B');
INSERT INTO `questions` VALUES (54, '《西游记中》奔波儿灞与灞波儿奔中的灞波儿奔是什么鱼变成的妖精？', '黑鱼精', '鲶鱼精', '鲤鱼精', 'A');
INSERT INTO `questions` VALUES (55, '鸵鸟遇到危险时怎么办？', '跑', '把头埋进沙子', '把头低向地面', 'C');
INSERT INTO `questions` VALUES (56, '小明今年5岁，小明的妹妹今年4岁，请问5年后小明比他妹妹大几岁？', '5岁', '1岁', '6岁', 'C');
INSERT INTO `questions` VALUES (57, '完全在我国境内的8000米以上的山峰是哪一座？', '珠穆拉玛峰', '希夏邦马峰', '干城章嘉峰', 'B');
INSERT INTO `questions` VALUES (58, '大约在冬季这首歌曲原唱还唱过哪首歌曲？', '开开心心', '齐齐秦秦', '夜夜夜夜', 'C');
INSERT INTO `questions` VALUES (59, '2017年10月，美国宣布退出了联合国的哪一组织？', '教科文组织', '联合组织', '联合会组织', 'A');
INSERT INTO `questions` VALUES (60, '最早婚礼上放鞭炮是为了？', '镇妖除邪', '求子', '增添喜庆', 'A');
INSERT INTO `questions` VALUES (61, '2000年夏季奥运会是在哪个城市举办的？', '悉尼', '雅典', '米兰', 'A');
INSERT INTO `questions` VALUES (62, '《尚书》中的“尚”是什么意思？', '上古', '崇尚', '官名', 'A');
INSERT INTO `questions` VALUES (64, '在动画片《舒克贝塔历险记》中，舒克的职业是？', '飞行员', '宇航员', '列车员', 'A');
INSERT INTO `questions` VALUES (65, '以下哪个星球不属于太阳系的“八大行星”？', '水星', '海王星', '天狼星', 'C');
INSERT INTO `questions` VALUES (66, '成语“卧冰求鲤”的故事发生在我国哪个省份？', '山东', '吉林', '河北', 'A');
INSERT INTO `questions` VALUES (67, '“蜀汉三杰”指的是哪三个人？', '刘备、关羽、张飞', '曹操、刘备、孙权', '诸葛亮、关羽、张飞', 'C');
INSERT INTO `questions` VALUES (68, '下面的城市哪个是沿海城市？', '利物浦', '芝加哥', '布拉格', 'A');
INSERT INTO `questions` VALUES (69, '发源于我国唐古拉山的湄公河流经了几个国家？', '5个', '6个', '7个', 'B');
INSERT INTO `questions` VALUES (70, '在歌曲《火锅底料》中，gai一共提到了多少遍“老子吃火锅，你吃火锅底料”？', '5', '500', '10000', 'A');
INSERT INTO `questions` VALUES (71, '歌手林俊杰出生在哪个国家？', '中国', '新加坡', '马来西亚', 'B');
INSERT INTO `questions` VALUES (72, '以下获得过诺贝尔文学奖的作家是？', '村上春树', '加藤嘉一', '石黑一雄', 'C');
INSERT INTO `questions` VALUES (73, '小猪麦兜向往“蓝天白云，椰林树影”的地方是哪个岛？', '马尔代夫', '海南岛', '西西里岛', 'A');
INSERT INTO `questions` VALUES (74, '歌曲《光辉岁月》是beyond乐队写给谁的？', '曼德拉', '祖玛', '穆加贝', 'A');
INSERT INTO `questions` VALUES (75, '下面的球员中，被我国球迷叫做“小飞侠”的是哪位？', '麦迪', '科比', '姚明', 'B');
INSERT INTO `questions` VALUES (76, '李亚鹏王菲夫妇倡导发起的“嫣然天使基金”是专门资助哪种病的患者？', '唇腭裂', '小儿麻痹', '夜盲症', 'A');
INSERT INTO `questions` VALUES (77, '香港四大天王指的是刘德华.张学友.郭富城和谁？', '陈奕迅', '谭咏麟', '黎明', 'C');
INSERT INTO `questions` VALUES (78, '世界上被称为“教育王国”的是哪一个国家？', '中国', '以色列', '日本', 'B');
INSERT INTO `questions` VALUES (79, '霓裳羽衣是哪个朝代的戏曲？', '唐', '宋', '五代十国', 'A');
INSERT INTO `questions` VALUES (80, '网球拍+网球 一共11美元，球拍比球贵10美元，问网球多少钱？', '1美元', '5美元', '0.5美元', 'C');
INSERT INTO `questions` VALUES (81, '我国是哪个时期进入奴隶社会的？', '夏', '商', '战国', 'A');
INSERT INTO `questions` VALUES (82, '在我国习俗中，压岁钱应该放在哪里？', '别人的银行账户里', '商场的包包里', '枕头下', 'C');
INSERT INTO `questions` VALUES (83, '国际礼仪中，鸣放礼炮都是单数还是双数？', '单数', '双数', '都可以', 'A');
INSERT INTO `questions` VALUES (84, '86版西游记共有多少集？', '40集', '25集', '60集', 'B');
INSERT INTO `questions` VALUES (85, '看鱼鳞能识鱼龄，鱼鳞上的一圈是表示？', '半岁', '一岁', '两岁', 'A');
INSERT INTO `questions` VALUES (86, '“沉鱼落雁，闭月羞花”中的“落雁”形容的是古代四大美女中的哪位？', '王昭君', '西施', '貂蝉', 'A');
INSERT INTO `questions` VALUES (87, '小苏打是碳酸氢钠，那么大苏打是什么？', '硫酸钠', '硫代硫酸钠', '亚硝酸钠', 'B');
INSERT INTO `questions` VALUES (88, '现在电影院热映电影前任攻略3的投资方是？', '华谊兄弟', '光线传媒', '万达影业', 'A');
INSERT INTO `questions` VALUES (89, ' 以下哪种食物致癌物最多？', '麻辣火锅', '炸鸡', '烤羊肉串', 'C');
INSERT INTO `questions` VALUES (90, '螺蛳粉起源于哪个城市的小吃？', '柳州市', '桂林市', '泉州市', 'A');
INSERT INTO `questions` VALUES (91, '中国历史上第一个统一的，中央集权的封建王朝是什么？', '秦朝', '唐朝', '宋朝', 'A');
INSERT INTO `questions` VALUES (92, '科学研究表明，室外健身最佳的时间是？', '下午或傍晚', '早晨和下午', '早晨和晚上', 'A');
INSERT INTO `questions` VALUES (93, '下面哪个银行不是中国五大银行？', '交通银行', '中国农业银行', '中国人民银行', 'C');
INSERT INTO `questions` VALUES (94, '《东北人都是活雷锋》最后一句台词是？', '翠花，上咸菜', '翠花，上酸菜', '翠花，上榨菜', 'B');
INSERT INTO `questions` VALUES (95, '石头城遗址是下列哪个城市的？', '石家庄', '南京', '唐山', 'B');
INSERT INTO `questions` VALUES (96, '塑料在自然界可停留多少年？', '10-20年', '50-100年', '100-200年', 'C');
INSERT INTO `questions` VALUES (97, '武侠小说中的武器“玄铁重剑”中，“玄”表示哪种颜色？', '白色', '黑色', '蓝色', 'B');
INSERT INTO `questions` VALUES (98, '孙中山的籍贯是？', '中山', '南京', '长沙', 'A');
INSERT INTO `questions` VALUES (99, '中国最早的消防队出现在哪个朝代？', '清代', '新中国成立后', '民国', 'A');
INSERT INTO `questions` VALUES (100, '阐述了“宇宙起源”的《时间简史》的作者是？', '霍金', '爱因斯坦', '特斯拉', 'A');
INSERT INTO `questions` VALUES (101, '以下哪种植物的果实可以做成肥皂？', '香樟', '香椿', '皂荚', 'C');
INSERT INTO `questions` VALUES (102, '俗语“铁公鸡”是形容一个人？', '嘴硬', '固执', '抠门', 'C');
INSERT INTO `questions` VALUES (104, '国际象棋共有多少颗棋子？', '30颗', '32颗', '34颗', 'B');
INSERT INTO `questions` VALUES (105, '有才出题官汪涵在2015年《我是歌手》上为谁救场而成为经典？', '韩红', '古巨基', '孙楠', 'C');
INSERT INTO `questions` VALUES (106, '诗句“两情若是久长时，又岂在朝朝暮暮”是歌颂哪两个人的爱情故事？', '牛郎织女', '梁山伯与祝英台', '许仙和白娘子', 'A');
INSERT INTO `questions` VALUES (107, '一个正方形的周长是200厘米，那边长是多少分米？', '4', '5', '50', 'B');
INSERT INTO `questions` VALUES (108, '食品芝士的主要原料是什么？', '牛奶', '大豆', '芝麻', 'A');
INSERT INTO `questions` VALUES (109, '以下哪首歌曲不是我们有颜出题官谢娜演唱的音乐作品？', '菠萝菠萝蜜', '给不了的幸福', '九妹', 'C');
INSERT INTO `questions` VALUES (110, '可乐的最初用途是什么？', '治病', '解渴', '调味', 'A');
INSERT INTO `questions` VALUES (111, '英语中“Love me,love my（）”对应的汉语中“爱屋及乌”？', 'dog', 'cat', 'mom', 'A');
INSERT INTO `questions` VALUES (112, '以下哪个法语单词不是“你好”的意思？', 'bongjour', 'merci', 'salut', 'B');
INSERT INTO `questions` VALUES (113, '下列哪个人不是“神盾局”的前身——“战略科学军团”的成员？', '佩吉.卡特', '尼克.福瑞', '霍华德斯塔克', 'B');
INSERT INTO `questions` VALUES (114, '成语“韦编三绝”中“韦”字是指什么？', '牛皮', '苇草', '竹简', 'A');
INSERT INTO `questions` VALUES (115, '以下哪个国家的国徽包含了椰枣树的元素？', '卡塔尔', '阿拉伯联合酋长国', '沙特阿拉伯', 'C');
INSERT INTO `questions` VALUES (116, '香奈儿五号香水的中调是什么？', '玫瑰，香草，麝香', '玫瑰，依兰，鸢尾', '玫瑰，迷迭香，薰衣草', 'B');
INSERT INTO `questions` VALUES (117, '数字2与3的最小公倍数用二进制怎么表示？', '110', '111', '110110', 'A');
INSERT INTO `questions` VALUES (118, '王力宏演唱《十二生肖》的春晚是什么生肖年的春晚？', '龙', '蛇', '马', 'B');
INSERT INTO `questions` VALUES (119, '《贫民窟的百万富翁》是哪个国家的电影？', '印度', '英国', '美国', 'B');
INSERT INTO `questions` VALUES (120, '外号TMAC的NBA球星没有效力过下面哪支球队？', '克利夫兰骑士', '多伦多猛龙', '青岛雄鹰', 'A');
INSERT INTO `questions` VALUES (121, '从三双不同袜子中任意取出两只，恰好是同一双的概率是？', '1/3', '1/5', '1/6', 'B');
INSERT INTO `questions` VALUES (122, '《哈利.波特》系列小说的倒数第三集叫什么名字？', '《哈利.波特与混血王子》', '《哈利.波特与火焰杯》', '《哈利.波特与凤凰社》', 'C');
INSERT INTO `questions` VALUES (123, '达.芬奇名画《最后的晚餐》中从左数第11个人是谁？', '犹大', '耶稣', '马太', 'C');
INSERT INTO `questions` VALUES (124, '电影《功夫》中周星驰饰演的“星仔”立志要加入哪个帮派？', '剪刀帮', '斧头帮', '石头帮', 'B');
INSERT INTO `questions` VALUES (125, '我国体检通用的“新国际视力表”上使用的是那个字母？', 'D', 'E', 'F', 'B');
INSERT INTO `questions` VALUES (126, '散文篇《假如给我三天光明》是美国哪位盲人女作家的作品？', '海伦·凯勒', '玛格丽特·米切尔', '欧·亨利', 'A');
INSERT INTO `questions` VALUES (127, '我国的椰子大部分产自哪个省？', '海南', '福建', '广东', 'A');
INSERT INTO `questions` VALUES (128, '美国的“超级碗”是什么体育项目联赛的年度冠军赛？', '篮球', '棒球', '美式足球', 'C');
INSERT INTO `questions` VALUES (129, '“人生就像巧克力，没人知道下一块是什么味道”这句台词出于哪一部美国电影？', '阿甘正传', '肖生克的救赎', '当幸福来敲门', 'A');
INSERT INTO `questions` VALUES (130, '通常家用电器上，“off”表示的是什么意思？', '开', '关', '掉线', 'B');
INSERT INTO `questions` VALUES (131, '冬天玻璃上容易结冰花，那么冰花是结在玻璃的哪里？', '室内侧', '室外侧', '玻璃里面', 'A');
INSERT INTO `questions` VALUES (132, '源于基督教教义的千福年又名千禧年，下面哪位明星出生于千禧年？', '关晓彤', '易烊千玺', '吴磊', 'B');
INSERT INTO `questions` VALUES (133, '以下身体结构不是主要由蛋白质组成的是？', '头发', '牙齿', '指甲', 'B');
INSERT INTO `questions` VALUES (134, '被称为“大可汗”的是唐朝哪位皇帝？', '唐高祖', '唐玄宗', '唐太宗', 'C');
INSERT INTO `questions` VALUES (135, '贝多芬的《田园交响曲》又名“F大调第几交响曲”？', '五', '六', '九', 'B');
INSERT INTO `questions` VALUES (136, '歌曲《浮夸》《圣诞结》是哪位香港男歌手的代表作?', '张学友', '陈奕迅', '刘德华', 'B');
INSERT INTO `questions` VALUES (137, '俗语“四两拨千斤”中，体现了哪种物理原理？', '阿基米德原理', '杠杆原理', '相对论', 'B');
INSERT INTO `questions` VALUES (138, '陈凯歌导演的《无极》被网友戏称为一个什么引发的血案？', '馒头', '面包', '萝卜', 'A');
INSERT INTO `questions` VALUES (139, '化妆品中的BB霜是干什么用的？', '遮瑕', '卸妆', '擦屁股', 'A');
INSERT INTO `questions` VALUES (140, '“单独”的“单”作为姓氏时应该读成什么？', 'dān', 'chán', 'shàn', 'C');
INSERT INTO `questions` VALUES (141, '二战诺曼底登陆是指同盟国士兵渡过哪一个海峡前往法国？', '英吉利海峡', '直布罗陀海峡', '马六甲海峡', 'A');
INSERT INTO `questions` VALUES (142, '新海诚动漫《你的名字》中的女主角叫什么？', '泷泽萝拉', '宫水三叶', '滨崎步', 'B');
INSERT INTO `questions` VALUES (143, '“情人节”起源于？', '意大利', '法国', '美国', 'A');
INSERT INTO `questions` VALUES (144, '金球奖，金靴奖是体育界什么项目的奖项？', '乒乓球', '足球', '冰球', 'B');
INSERT INTO `questions` VALUES (145, '“仲夏”通常被我们用来形容农历几月份？', '四月', '五月', '六月', 'B');
INSERT INTO `questions` VALUES (146, '图像处理与修改软件photoshop是哪个公司的产品？', 'apple', 'arcSoft', 'adobe', 'C');
INSERT INTO `questions` VALUES (147, '香烟中的有害物质，尼古丁的名字最早来源于？', '地名', '人名', '植物名', 'B');
INSERT INTO `questions` VALUES (148, '我国《民法通则》规定，多少周岁以上的公民是成年人？', '16', '18', '20', 'B');
INSERT INTO `questions` VALUES (149, '火药是哪个国家发明的？', '中国', '日本', '美国', 'A');
INSERT INTO `questions` VALUES (150, '“一打”是指多少个？', '10', '11', '12', 'C');
INSERT INTO `questions` VALUES (151, '下列人物不是出自鲁迅文学作品的？', '鸣凤', '祥林嫂', '涓生', 'A');
INSERT INTO `questions` VALUES (152, '标志着新中国成立的历史事件？', '开国大典', '土地改革的完成', '第一届党代会的召开', 'A');
INSERT INTO `questions` VALUES (153, '酒精是哪种化学物质的俗称？', '甲醇', '乙醇', '甲醛', 'B');
INSERT INTO `questions` VALUES (154, '“红豆生南国”这句话来源于哪首诗？', '《红豆》', '《相思》', '《赠别》', 'B');
INSERT INTO `questions` VALUES (155, '下列哪种物质能提升皮肤胶原蛋白及弹力素蛋白的合成能力？', '葡聚糖', '灵芝三萜', '有机锗', 'A');
INSERT INTO `questions` VALUES (156, '中国民间传说“八仙过海”中唯一一位女性是谁？', '李夫人', '蓝采和', '何仙姑', 'C');
INSERT INTO `questions` VALUES (157, '“戛纳国际电影节”在哪一个国家举办的？', '法国', '美国', '英国', 'A');
INSERT INTO `questions` VALUES (158, '“有缘千里来相会，无缘对面手难牵”是哪首歌的歌词？', '《千年等一回》', '《新白娘子传奇》', '《渡情》', 'C');
INSERT INTO `questions` VALUES (159, '鹿角灵芝的苦味来自那种物质？', '灵芝多糖', '灵芝三萜', '灵芝腺苷', 'B');
INSERT INTO `questions` VALUES (160, '韩国的首都是？', '釜山   ', '仁川   ', '首尔', 'C');
INSERT INTO `questions` VALUES (161, '正月十五是中国哪个传统节日？', '元宵节   ', '中秋节    ', '端午节', 'A');
INSERT INTO `questions` VALUES (162, '黄果树瀑布位于哪个省？', '贵州省  ', '四川省     ', '广西省', 'A');
INSERT INTO `questions` VALUES (163, '河北省现在的省会是？', '石家庄     ', '保定      ', '承德', 'A');
INSERT INTO `questions` VALUES (164, '“鸡蛋仔”是哪个地区的传统街头小吃？', '广东      ', '台湾       ', '香港', 'C');
INSERT INTO `questions` VALUES (165, '市面上售卖的能有效提升免疫力的产品？', '红牛', '鹿角灵芝胶囊', '脑白金', 'B');
INSERT INTO `questions` VALUES (166, '足球比赛里的“帽子戏法”是什么意思？', '一名球员单场进三球     ', '球员带着帽子比赛    ', '换了三名替补', 'A');
INSERT INTO `questions` VALUES (167, '以下真菌中，哪种葡聚糖含量最高？', '野生灵芝', '猪苓', '鹿角灵芝', 'C');
INSERT INTO `questions` VALUES (168, '加拿大的首都是？', '渥太华        ', '温哥华     ', '多伦多', 'A');
INSERT INTO `questions` VALUES (169, '在 2017 年金马奖颁奖礼上，哪位演员获得了最佳女配角奖？', '惠英红       ', '文淇     ', '许玮甯', 'B');
INSERT INTO `questions` VALUES (170, '“七里香”在台湾是指哪种小吃？', '甜不辣      ', '臭豆腐      ', '鸡屁股', 'C');
INSERT INTO `questions` VALUES (171, '第一位两次在不同领域获得诺贝尔讲的人是？', '杨振宁       ', '田中耕一    ', '玛丽·居里', 'C');
INSERT INTO `questions` VALUES (172, '美国国旗上的小星星代表什么？', '州', '民族', '殖民地', 'A');
INSERT INTO `questions` VALUES (173, '土耳其的通用语言是？', '．土耳其语', '英语', '阿拉伯语', 'A');
INSERT INTO `questions` VALUES (174, '以下哪一位不是通过选秀节目成为歌手的 ?', '徐佳莹     ', '谭维维    ', '. 梁静茹', 'C');
INSERT INTO `questions` VALUES (175, '骆驼的驼峰是储存什么的？', '水', '脂肪', '食物', 'B');
INSERT INTO `questions` VALUES (176, '官方曾给米其林轮胎人「添加」了哪个家庭成员？', '妻子', '妈妈', '哥哥', 'A');
INSERT INTO `questions` VALUES (177, '扑克牌中黑桃Q的人物原型是谁？', '雅典娜', '圣女贞德', '玛利亚', 'A');
INSERT INTO `questions` VALUES (178, '螃蟹有几条腿？', '八条', '十条', '六条', 'B');
INSERT INTO `questions` VALUES (179, '“八小时工作制度”最早是在哪个国家出现的?', '英国', '美国', '意大利', 'A');
INSERT INTO `questions` VALUES (180, '兔子和乌龟比什么绝对不会输？', '跳远', '赛跑', '仰卧起坐', 'C');
INSERT INTO `questions` VALUES (181, '维纳斯是希腊神话中的？', '智慧女神', '爱神和美神', '自由女神', 'B');
INSERT INTO `questions` VALUES (182, '西游记》中的火焰山位于？', '甘肃', '新疆', '青海', 'B');
INSERT INTO `questions` VALUES (183, '李白笔下的“飞流直下三千尺，疑是银河落九天”指的是哪个风景区？', '华山', '庐山', '天姥山', 'B');
INSERT INTO `questions` VALUES (184, '唐代人可以称“父亲”为？', '伯伯', '哥哥', '大爷', 'B');
INSERT INTO `questions` VALUES (185, '\"红娘\"由来是出自下列哪部古典名剧？', '《琵琶记》', '《西厢记》', '《长生殿》', 'B');
INSERT INTO `questions` VALUES (186, '我国第一部有声影片是？', '《歌女红牡丹》', '《定军山》', '《玉人何处》', 'A');
INSERT INTO `questions` VALUES (187, '下列哪座山不属于我国四大佛山之一？', '雁荡山', '五台山', '九华山', 'A');
INSERT INTO `questions` VALUES (188, '奔驰汽车原产于哪一个国家?', '美国', '日本', '德国', 'C');
INSERT INTO `questions` VALUES (189, '北京大学的第一位校长是？', '严复', '蔡元培', '胡适', 'A');
INSERT INTO `questions` VALUES (190, '大汶口文化遗址在我国的什么地方？', '湖南', '山东', '甘肃', 'B');
INSERT INTO `questions` VALUES (191, '某消费者以180元的价格购买了一双皮鞋，进检验这双鞋是假冒产品，按 照《消费者权益保护法》的规定，经营者应当赔赏给消费者多少钱？', '360', '180', '3600', 'A');
INSERT INTO `questions` VALUES (192, '世界第一大教堂？', '圣彼得大教堂', '圣玛利亚教堂', '米兰大教堂', 'A');
INSERT INTO `questions` VALUES (193, '洲际导弹一般射程在多少公里以上?', '一千', '一万', '一百', 'B');
INSERT INTO `questions` VALUES (194, '“民为贵,社稷次之,君为轻”这句话出自', '《孟子》', '《孔子》', '《孙子》', 'A');
INSERT INTO `questions` VALUES (195, '不论是儿童、成年或老年缺钙都会影响健康，患各种疾病，钙的吸收与下面哪种维生素有关系？', '维生素B', '维生素C', '维生素D', 'C');
INSERT INTO `questions` VALUES (196, '奥运会旗是:\"五色环\"旗,其中黄色环代表？', '亚洲', '非洲', '美洲', 'A');
INSERT INTO `questions` VALUES (197, '味精的主要成分是?', '氯化钠', '谷氨酸钠', '醋酸', 'B');
INSERT INTO `questions` VALUES (198, '\"破釜沉舟\"这个成语出于哪次战争?', '赤壁之战', '长平之战', '巨鹿之战', 'C');
INSERT INTO `questions` VALUES (199, '世界上最大的宫殿是？', '故宫', '爱丽舍宫', '克里姆林宫', 'A');
INSERT INTO `questions` VALUES (200, '一般而言，肥胖是指超过理想体重的百分之多少?', '10%', '20%', '30%', 'B');
INSERT INTO `questions` VALUES (201, '平素体弱又不经常锻炼身体的人，当她（他）们从蹲位突然站起时，往往 出现头晕、眼前发黑是因为？', '贫血', '饥饿', '直立性高血压', 'C');
INSERT INTO `questions` VALUES (202, '《献血法》规定，献血者两次献血间隔时间不得少于?', '三个月', '六个月', '一年', 'B');
INSERT INTO `questions` VALUES (203, '具有止血功能的维生素是?', '维生素A ', '维生素E', '维生素K', 'C');
INSERT INTO `questions` VALUES (204, '世界上有很多种语言，大约有多少种？', '近2000种', '近3000种', '近4000种', 'B');
INSERT INTO `questions` VALUES (205, '世界哪一个国家的茶叶产量最多？', '中国', '日本', '印度', 'C');
INSERT INTO `questions` VALUES (206, '发烧时不宜喝什么饮料？', '果汁', '白开水', '浓茶', 'C');
INSERT INTO `questions` VALUES (207, '世界读书日是什么时候？', '2.13', '4.23', '6.21', 'B');
INSERT INTO `questions` VALUES (208, '“WHO”代表什么世界组织？', '世界绿色和平组织', '世界卫生组织', '世界贸易组织', 'B');
INSERT INTO `questions` VALUES (209, '以下历史事件中，与关羽无关的是?', '单刀赴会', '水淹七军', '七擒七纵', 'C');
INSERT INTO `questions` VALUES (210, '巴黎凯旋门是为纪念谁而建？', '丘吉尔', '拿破仑', '戴高乐', 'B');
INSERT INTO `questions` VALUES (211, '足球共有多少块补丁组成？', '32', '42', '52', 'A');
INSERT INTO `questions` VALUES (212, '弱冠指的是多少岁？', '二十', '十八', '十六', 'A');
INSERT INTO `questions` VALUES (213, '根据有关规定，职工的试用期最长不得超过', '三个月', '六个月', '一年', 'B');
INSERT INTO `questions` VALUES (214, '打蛇打七寸\"的七寸是指？', '咽喉', '心脏', '尾巴', 'B');
INSERT INTO `questions` VALUES (215, '我国古代称为“启明星”的是太阳系八大行星中的哪个？', '金星', '木星', '土星', 'A');
INSERT INTO `questions` VALUES (216, '我国第五套人民币上印着除了壮文，蒙古文，藏文，还有哪一种少数民族文字？', '哈萨克文', '维吾尔文', '满文', 'B');
INSERT INTO `questions` VALUES (217, '防毒面具是根据什么动物的脸部研制的？', '浪', '苍蝇', '猪', 'C');
INSERT INTO `questions` VALUES (218, '日常使用的电池上标有“AA”的是几号电池？', '5', '7', '1', 'A');
INSERT INTO `questions` VALUES (219, '天气预报：“今天阴有小雨。”你可知道小雨的降雨量为多少？', '10毫米以下', '10-20毫米', '20-50毫米', 'A');
INSERT INTO `questions` VALUES (220, '英超的全称是？', '英格兰足球超级联赛', '英国足球超级联赛', '英德足球超级联赛', 'A');
INSERT INTO `questions` VALUES (221, '我国第一个接到奥运会邀请书的人是？', '光绪', '李鸿章', '慈禧', 'A');
INSERT INTO `questions` VALUES (222, '五禽戏的发明者是?', '扁鹊', '喜来乐', '华佗', 'C');
INSERT INTO `questions` VALUES (223, '钓鱼岛从何时开始就明确为我国的领土？', '明朝', '唐朝', '宋朝', 'A');
INSERT INTO `questions` VALUES (224, '世界上最长的海峡是?', '莫桑比克海峡', '马六甲海峡', '土耳其海峡', 'A');
INSERT INTO `questions` VALUES (225, '双十二事变又称为？', '皖南事变', '卢沟桥事变', '西安事变', 'C');
INSERT INTO `questions` VALUES (226, '“一问三不知”出自《左传》，说的是哪三不知呢？', '起因，经过，结果', '天文，地理，文学', '孔子，孟子，老子', 'A');
INSERT INTO `questions` VALUES (227, '“月上柳梢头，人约黄昏后”描写的是我国哪一经典传统节日呢？', '元宵节', '端午节', '七夕节', 'A');
INSERT INTO `questions` VALUES (228, '义勇军进行曲作者？', '聂耳', '冼星海', '田汉', 'A');
INSERT INTO `questions` VALUES (229, 'Java之父是?', '詹姆斯·高斯林', '约翰·罗梅洛', '比尔·盖茨', 'A');
INSERT INTO `questions` VALUES (230, '下列海洋中哪一个是我国最大的海?', '南海', '东海', '黄海', 'A');
INSERT INTO `questions` VALUES (231, '正方形的四个角都是？', '锐角', '直角', '钝角', 'B');
INSERT INTO `questions` VALUES (232, '历史故事“霸王别姬”中的“霸王”指的是？', '曹操', '刘邦', '项羽', 'C');
INSERT INTO `questions` VALUES (233, '解放战争中，舍身炸碉堡的革命英雄是？', '黄继光', '邱少云', '董存瑞', 'C');
INSERT INTO `questions` VALUES (234, '看电视时，屏幕上显示的“live”字样的意思是？', '重播', '直播', '录播', 'B');
INSERT INTO `questions` VALUES (235, '生活中“煤气中毒”主要指的是哪种气体进入人体呼吸道而发生的？', '氯气', '二氧化碳', '一氧化碳', 'C');
INSERT INTO `questions` VALUES (236, '十二生肖中排在羊前面一个的是什么动物？', '猴', '马', '蛇', 'B');
INSERT INTO `questions` VALUES (237, '代表作之一是《蒙娜丽莎的眼泪》的歌手是？', '林志颖', '林志炫', '林志玲', 'B');
INSERT INTO `questions` VALUES (238, '苏轼《赤壁赋》中“其声呜呜然，如怨如慕，如泣如诉”描述的是哪种乐器的声音？', '琵琶', '古筝', '箫', 'C');
INSERT INTO `questions` VALUES (239, '下列哪一项不属于哺乳动物？', '老虎 ', '狗', '鸡', 'C');
INSERT INTO `questions` VALUES (240, '等腰直角三角形的两个底角之和是多少度？', '60度', '90度', '120度', 'B');
INSERT INTO `questions` VALUES (241, '2018年的2月有多少天？', '28', '29', '30', 'A');
INSERT INTO `questions` VALUES (242, '白炽灯是哪位科学家发明的？', '特斯拉', '爱迪生', '牛顿', 'B');
INSERT INTO `questions` VALUES (243, '我国神话传说中，谁开天辟地？', '盘古', '伏羲', '女娲', 'A');
INSERT INTO `questions` VALUES (244, '下列哪种球类比赛采用11分赛制？', '乒乓球', '羽毛球', '排球', 'A');
INSERT INTO `questions` VALUES (245, '美国总统特朗普的大女儿叫什么？', '梅拉尼娅', '伊万卡', '蒂芙尼', 'B');
INSERT INTO `questions` VALUES (246, '一节干电池的电压是多少？', '1.5V', '1.7V', '2.0V', 'A');
INSERT INTO `questions` VALUES (247, '湄公河不经过以下哪个国家？', '老挝', '缅甸', '印度', 'C');
INSERT INTO `questions` VALUES (248, '古诗“两个黄鹂鸣翠柳”的下一句是？', '疑是银河落九天', '一行白鹭上青天', '门泊东吴万里船', 'B');
INSERT INTO `questions` VALUES (249, '08年北京奥运会主题曲是？', '北京祝福你', '北京欢迎你', '北京我爱你', 'B');
INSERT INTO `questions` VALUES (250, '四川话“摆龙门阵”是什么意思？', '拉拉家常', '打打麻将', '聚众斗殴', 'A');
INSERT INTO `questions` VALUES (251, '伦敦城市标志之一的“伦敦眼”是什么建筑？', '塔桥', '摩天轮', '风车', 'B');
INSERT INTO `questions` VALUES (252, '动画电影《疯狂动物城》中，警官朱迪是一只？', '兔子', '狐狸', '熊', 'A');
INSERT INTO `questions` VALUES (253, '“玄武门之变”发生在哪位皇帝在位期间？', '唐太宗', '唐高宗', '唐高祖', 'C');
INSERT INTO `questions` VALUES (254, '“生的伟大，死的光荣”是毛主席对以下哪个人物的评价？', '雷锋', '刘胡兰', '邱少云', 'B');
INSERT INTO `questions` VALUES (255, '在田径运动男子110米跨栏中，运动员一共要跨过多少个栏？', '9', '10', '11', 'B');
INSERT INTO `questions` VALUES (256, '从职责上看，美国的国务卿相当于我国的？', '外交部长', '国务院总理', '中央军委主席', 'A');
INSERT INTO `questions` VALUES (257, '“毛氏红烧肉”是哪个地方的美食？', '陕西延安', '湖南湘潭', '贵州遵义', 'B');
INSERT INTO `questions` VALUES (258, '被后世称为“八大山人”的是几个人？', '八个', '四个', '一个', 'C');
INSERT INTO `questions` VALUES (259, '“冲冠一怒为红颜”此处的“红颜”是指？', '妲己', '陈圆圆', '李师师', 'B');
INSERT INTO `questions` VALUES (260, '《人在囧途》的导演是谁？', '徐铮', '叶伟民', '王晶', 'B');
INSERT INTO `questions` VALUES (261, '“心有猛虎，细嗅蔷薇”是由哪位诗人由英文翻译至中文的？', '余秋雨', '郭沫若', '余光中', 'C');
INSERT INTO `questions` VALUES (262, '“臭鳜鱼”是哪个省的著名菜肴？', '安徽省', '湖北省', '江西省', 'A');
INSERT INTO `questions` VALUES (263, '唐宋八大家中有几个唐朝人？', '2', '3', '4', 'A');
INSERT INTO `questions` VALUES (264, '每到春天，柳絮就会漫天飞舞，那么柳絮其实是柳树的什么？', '种子', '茎', '花', 'A');
INSERT INTO `questions` VALUES (265, '世界上面积最大的湖是哪一个？', '里海 ', '贝加尔湖', '苏必利尔湖', 'A');
INSERT INTO `questions` VALUES (266, '以下哪个人物不是出自于金庸的小说？', '杨过', '李寻欢', '谢烟客', 'B');
INSERT INTO `questions` VALUES (267, '有“小提琴之王”之称的作曲家是：', '帕格尼尼', '贝多芬', '海顿', 'A');
INSERT INTO `questions` VALUES (268, '中国第一座佛教寺院是哪一座？', '北京潭柘寺', '洛阳白马寺', '五台山清凉寺', 'B');
INSERT INTO `questions` VALUES (269, '由于钙质流失，容易出现维生素D缺乏症，导致腰腿发软，骨质疏松，下列哪项不是补充维生素D？', '经常晒太阳', '多食用动物肝脏', '多吃猕猴桃等水果', 'C');
INSERT INTO `questions` VALUES (270, '最古老的医院是设在： ', '学校里', '教堂里', '宫廷里', 'B');
INSERT INTO `questions` VALUES (271, '杜康酒的产地在我国的：', '河南', '山西', '陕西', 'A');
INSERT INTO `questions` VALUES (272, '“一衣带水”的水是指哪条河流？ ', '长江', '黄河', '珠江', 'A');
INSERT INTO `questions` VALUES (273, '文学名篇《人变兽》的作者是哪一位作家？ ', '鲁迅', '矛盾', '徐志摩', 'C');
INSERT INTO `questions` VALUES (274, '在下列足球明星中，有“独狼”称号的是谁？', '古力特', '罗西纳尔多', '罗马里奥', 'C');
INSERT INTO `questions` VALUES (275, '在小说《侠客行》中，石破天的玄铁令是从那里得来的？ ', '一块烧饼中', '一本书中', '一口井里', 'A');
INSERT INTO `questions` VALUES (276, '被称为“英雄树”的是哪种植物？', '龙眼', '木棉', '富贵菊', 'B');
INSERT INTO `questions` VALUES (277, '中国的传统手工艺---景泰蓝在哪一历史时期发展最快？', '明景泰年间', '明宣德年间', '明万历年间', 'A');
INSERT INTO `questions` VALUES (278, '“景泰蓝”是何地的特种工艺？ ', '北京', '上海', '南京', 'A');
INSERT INTO `questions` VALUES (279, '贝多芬一生创作了多少首钢琴奏鸣曲？', '27', '28', '32', 'C');
INSERT INTO `questions` VALUES (280, '五子棋段位制最高为：', '一段', '六', '九段', 'C');
INSERT INTO `questions` VALUES (281, '按有关法律规定，经营者可以从事的抽奖式有奖销售，最高奖的奖金额的限度是：', '五千元人民币', '五万人民币', '一百万人民币', 'A');
INSERT INTO `questions` VALUES (282, '我们日常的主食基本上属于什么食物？', '酸性食物', '碱性食物', '中性食物', 'A');
INSERT INTO `questions` VALUES (283, '公元前594年，实行“初税亩”，按亩收税的国家是：', '楚国', '鲁国', '郑国', 'B');
INSERT INTO `questions` VALUES (284, '中国虽然不是双姓大国，但还是有不少双姓，请问以下哪个不是双姓？', '东郭', '诸葛', '三台', 'C');
INSERT INTO `questions` VALUES (285, '《阿里山的姑娘》是哪个少数民族的民歌？', '苗族民歌', '彝族民歌', '高山族民歌', 'C');
INSERT INTO `questions` VALUES (286, '青蛙除了用肺外还用什么器官呼吸？', '肌肉', '皮肤', '脾脏', 'B');
INSERT INTO `questions` VALUES (287, '下列影片中，以歌颂少数民族新生活为题材的是：', '《李双双》', '《洞箫横吹》', '《达吉和她的父亲》', 'C');
INSERT INTO `questions` VALUES (288, '在江浙一带最流行的地方戏曲是：', '越剧', '黄梅戏', '京剧', 'A');
INSERT INTO `questions` VALUES (289, '科学家把猪、牛、羊、马一起关在施放了有毒氯气的环境中作试验，它们中谁逃脱了厄运？', '猪', '牛', '羊', 'A');
INSERT INTO `questions` VALUES (290, '“运斤成风”比喻技艺神异，手法熟练，这个“斤”字是指：', '石墩', '铜锤', '斧子', 'C');
INSERT INTO `questions` VALUES (291, '《嘎达梅林》是哪个民族的叙事歌曲？', '维吾尔族', '哈萨克族', '蒙古族', 'C');
INSERT INTO `questions` VALUES (292, '我国的哪一个城市素有“日光之城”的美称？', '厦门', '青岛', '拉萨', 'C');
INSERT INTO `questions` VALUES (293, '“何处招魂，香草还生三户地；当年呵壁，湘流应识九歌心”，这幅对联说的是：', '贾谊', '诸葛亮', '屈原', 'C');
INSERT INTO `questions` VALUES (294, '世界上最深的海沟位于：', '太平洋', '大西洋', '北冰洋', 'A');
INSERT INTO `questions` VALUES (295, '国际上用“K”表示含金量，18K表示含金量为：', '90%', '83%', '75%', 'C');
INSERT INTO `questions` VALUES (296, '“德育、智育、体育三者，为教育缺一不可之物”是我国近代哪位著名历史人物说的话？', '梁启超', '蔡元培', '周恩来', 'A');
INSERT INTO `questions` VALUES (297, '民间故事“八仙过海”中的“八仙”和谁属一教派？', '太上老君', '观音菩萨', '摩西', 'A');
INSERT INTO `questions` VALUES (298, '“似曾相识燕归来”的上一句是： ', '无可奈何花落去', '相逢一笑泯恩仇', '东边日出西边雨', 'A');
INSERT INTO `questions` VALUES (299, '避雷针的发明者是：', '富兰克林', '爱迪生', '伏打', 'A');
INSERT INTO `questions` VALUES (300, '为什么汗水湿透的背心不能用热水洗？', '汗水里含有少量蛋白', '避免把衣服烫坏', '只有特殊料的衣服才不宜用热水洗', 'A');
INSERT INTO `questions` VALUES (301, '“孺子牛”原指：', '小牛', '小孩牵的牛', '小孩牵人假扮的牛', 'C');
INSERT INTO `questions` VALUES (302, '“民告官”是以下哪种法律行为的俗称？ ', '刑事诉讼', '民事诉讼', '行政诉讼', 'C');
INSERT INTO `questions` VALUES (303, '七大洲中面积最小的是：', '非洲', '大洋洲', '南极洲', 'C');
INSERT INTO `questions` VALUES (304, '以下哪一个阶级，不属于法国大革命前的第三等级？', '农民', '下级教士', '资产阶级', 'B');
INSERT INTO `questions` VALUES (305, '是哪国人最先制作出了牛奶巧克力？', '英国', '西班牙', '瑞士', 'C');
INSERT INTO `questions` VALUES (306, '“轻于鸿毛”中的鸿毛是哪种动物的毛？', '羊', '大雁', '鸡', 'B');
INSERT INTO `questions` VALUES (307, '从抹香鲸体内提炼出的香料是： ', '百里香', '沉水香', '龙涎香', 'C');
INSERT INTO `questions` VALUES (308, '树的年轮的形成和下列哪项条件有直接关系？ ', '雨水', '温度', '地势', 'A');
INSERT INTO `questions` VALUES (309, '我们日常吃的紫菜属于下列哪种藻类？ ', '红藻', '褐藻', '绿藻', 'A');
INSERT INTO `questions` VALUES (310, '现在大力保护大气臭氧层，原因是臭氧层能够吸收：', '二氧化碳', '高能紫外线', '一氧化碳', 'B');
INSERT INTO `questions` VALUES (311, '“问君能有几多愁”诗句的下句是： ', '才下眉头，却上心头', '恰似一江春水向东流', '剪不断，理还乱', 'B');
INSERT INTO `questions` VALUES (312, '通常鱼在一年四季中什么时候长得最慢？', '春天', '夏天', '冬天', 'C');
INSERT INTO `questions` VALUES (313, '下列名称不属于二十四节气的是：', '谷雨', '芒种', '大雪', 'C');
INSERT INTO `questions` VALUES (314, '王洛宾整理的《花儿与少年》是哪个地区的民歌？', '新疆', '西藏', '内蒙', 'C');
INSERT INTO `questions` VALUES (315, '穿什么颜色的衣服的人更容易挨蚊子叮？ ', '黑色', '白色', '黄色', 'A');
INSERT INTO `questions` VALUES (316, '语言中最小的声音和意义的结合体称为：', '音素', '音节', '语素', 'C');
INSERT INTO `questions` VALUES (317, '人体呼吸系统的组成是：', '鼻腔和气管', '气管和肺', '呼吸道和肺', 'C');
INSERT INTO `questions` VALUES (318, '使用电磁波对金属工件内部进行检测的方法叫：', '超声检测', '射线探伤', '渗透探查', 'B');
INSERT INTO `questions` VALUES (319, '藏历新年，人们见面时都要说“扎西德勒”是什么意思？', '吉祥如意', '新年快乐', '你真漂亮', 'A');
INSERT INTO `questions` VALUES (320, '“黄果树瀑布”位于哪个省？', '湖南', '贵州', '四川', 'B');
INSERT INTO `questions` VALUES (321, '举重时运动员为什么搓白粉？', '使手变的粗糙', '吸取手上的汗', '刺激肌肉', 'B');
INSERT INTO `questions` VALUES (322, '当前很多高科技公司都设了CIO这个职位，CIO的意思是：', '首席执行官', '首席信息官', '首席技术官', 'B');
INSERT INTO `questions` VALUES (323, '照片中的人有时会出现红眼，眼中的红色来自哪里？ ', '太阳光', '红色灯光', '人的眼睛', 'C');
INSERT INTO `questions` VALUES (324, '下令“破釜沉舟”的我国古代将领是：', '项庄', '项羽', '刘邦', 'B');
INSERT INTO `questions` VALUES (325, '最简单的有机化合物是：', '甲烷', '甲醛', '甲烯', 'A');
INSERT INTO `questions` VALUES (326, '有权做出批准或决定逮捕决定的国家机关是？', '公安局', '司法局', '人民检察院', 'C');
INSERT INTO `questions` VALUES (327, '我国古代《二十四史》的第一部是：', '史记', '左传', '春秋', 'A');
INSERT INTO `questions` VALUES (328, 'ISO14000认证是哪一方面的认证？ ', '商业', '交通', '环保', 'C');
INSERT INTO `questions` VALUES (329, '下列哪一项不属于华表曾经具有的功能？', '标示道路', '发表意见', '悬挂路灯', 'C');
INSERT INTO `questions` VALUES (330, '下列属于哺乳动物的是？', '恐龙', '蝙蝠', '文昌鱼', 'B');
INSERT INTO `questions` VALUES (331, '中国在国际货币基金组织中属于：', '观察员', '正式成员', '准成员', 'B');
INSERT INTO `questions` VALUES (332, '“问世间，情是何物，直教生死相许”语出： ', '李莫愁', '金庸', '元好问', 'C');
INSERT INTO `questions` VALUES (333, '下列不属于我国西部大开发的省份是：', '青海', '陕西', '山西', 'C');
INSERT INTO `questions` VALUES (334, '世界上的哪个国家有“黄金海岸”之称？', '西班牙', '加纳', '秘鲁', 'B');
INSERT INTO `questions` VALUES (335, '少林寺位于五岳中的哪一岳？', '东岳', '西岳', '中岳', 'C');
INSERT INTO `questions` VALUES (336, '最初在文学中三部曲：', '只有悲剧没有喜剧', '只有喜剧没有悲剧', '只有议论文没有小说', 'A');
INSERT INTO `questions` VALUES (337, '世界卫生组织的新健康标准为“五好三良”，请问下列哪项不属于“五好”的范围？', '胃口好、不挑食', '睡眠好', '头脑好、思维敏捷', 'C');
INSERT INTO `questions` VALUES (338, '世界电信日是哪一天？ ', '5月17日', '6月17日', '4月17日', 'A');
INSERT INTO `questions` VALUES (339, '世界环境日是哪一天？', '3月12日', '3月5日', '6月5日', 'C');
INSERT INTO `questions` VALUES (340, '世界地球日是哪一天？', '3月21日', '4月22日', '4月23日', 'B');
INSERT INTO `questions` VALUES (341, '“大夫”在我国古代是指：', '医生', '侍卫', '官职', 'C');
INSERT INTO `questions` VALUES (342, '英国占领加拿大之后将当地的法国人怎样了？', '全部杀死', '驱逐出境', '把他们赶到遥远的加拿大西部', 'B');
INSERT INTO `questions` VALUES (343, '“Moonlighting”是什么意思？', '月光下苦读', '玩土著人发明的“月光灯”', '晚上的第二职业', 'C');
INSERT INTO `questions` VALUES (344, '连接几段网线以增加距离时，使用哪件设备最佳？', 'ＢＮＣ接头', '集线器', '中继器', 'C');
INSERT INTO `questions` VALUES (345, '按照我国合同法的规定，当事人对合同变更的内容约定不明确时：', '推定自始没有订立合同', '视为合同解除', '确定为未变更', 'C');
INSERT INTO `questions` VALUES (346, '著名水城威尼斯共有118个：', '水道', '小岛', '桥梁', 'B');
INSERT INTO `questions` VALUES (347, '著名水城威尼斯共有多少个小岛？ ', '118', '128', '98', 'A');
INSERT INTO `questions` VALUES (348, '最早的冷冻机以什么为制冷剂？', '氨', '氮', '乙醚', 'C');
INSERT INTO `questions` VALUES (349, '下列哪项不是我国《消费者权益保护法》中规定的消费者的权利？', '保障安全权', '提供信息权', '公平交易权', 'B');
INSERT INTO `questions` VALUES (350, ' 适量补充下列哪种元素可防治粉刺? ', '铁', '锌', '钙', 'B');
INSERT INTO `questions` VALUES (351, ' 古代五音？？宫、商、角、徵、羽，相当于现行简谱上的： ', '1、2、3、4 、5', '1、2、3、5、6', '1、2、3、4、7', 'B');
INSERT INTO `questions` VALUES (352, ' 我国的长绒棉主要产在： ', '新疆', '内蒙', '甘肃', 'A');
INSERT INTO `questions` VALUES (353, ' 法国画家大卫的《马拉之死》是一幅： ', '肖像画', '历史画', '你告诉我', 'B');
INSERT INTO `questions` VALUES (354, ' 《楚辞》中有“兰膏照烛”一句。这里点灯用的“膏”是一种： ', '动物油', '植物油', '煤油', 'A');
INSERT INTO `questions` VALUES (355, ' \"海的女儿”是哪个城市的城徽？', '哥本哈根', '华沙', '平壤', 'A');
INSERT INTO `questions` VALUES (356, ' 近几年我国邮票上的邮政志铭是：', '中国人民邮政', '中国邮政', 'china邮政', 'B');
INSERT INTO `questions` VALUES (357, ' 下列王朝中统治时间最短的是： ', '秦朝', '隋朝', '西晋', 'A');
INSERT INTO `questions` VALUES (358, ' 人类最早的“精子库”是为谁而建的？ ', '不育男子', '参战士兵', '单身贵族', 'B');
INSERT INTO `questions` VALUES (359, ' 比赛中甲队要戴白帽子，乙队要戴蓝帽子，守门员要戴红帽子。这项比赛是：', '冰球比赛', '橄榄球比赛', '水球比赛', 'C');
INSERT INTO `questions` VALUES (360, ' 掷出一对点数一样的骰子的可能性是：', '1/2', '1/3', '1/6', 'C');
INSERT INTO `questions` VALUES (361, ' 华表的柱头有一蹲兽，其中头朝外的叫： ', '望帝归', '望帝出', '你告诉我', 'A');
INSERT INTO `questions` VALUES (362, ' 商品条形码前三位数是“690\"，表示什么？', '商品质量', '中国生产', '制造厂商', 'B');
INSERT INTO `questions` VALUES (363, ' 国画《愚公移山》的作者是： ', '齐白石', '李可染', '徐悲鸿', 'C');
INSERT INTO `questions` VALUES (364, ' 小康目前有两个标准：一个是以食物消费为参照，食物消费支出降到家庭收入的50%；另一个标准 ', '800元人民币', '800美元', '1600元人民币', 'B');
INSERT INTO `questions` VALUES (365, ' 甲、乙、丙三人设立合伙企业，下列哪项不能作为合伙人的出资？ ', '货币', '土地所有权', '实物使用权', 'B');
INSERT INTO `questions` VALUES (366, ' 一些小轿车的尾部装有翘起的板，这种板可以使汽车： ', '形成向上的升力，减少车轮与路面的摩擦，行驶得更快', '形成向下的压力，使车轮与路面的附着力增大，从而使汽车保持良好的操作性', '你告诉我', 'B');
INSERT INTO `questions` VALUES (367, ' 黑啤酒的突出香气是什么香？', '麦芽香', '酒花清香', '你告诉我', 'A');
INSERT INTO `questions` VALUES (368, ' “波谲云诡”最初是用来形容：', '气候', '战场', '房屋', 'C');
INSERT INTO `questions` VALUES (369, ' 放大镜的设计原理是采用了：', '凸透镜', '凹透镜', '你告诉我', 'A');
INSERT INTO `questions` VALUES (370, ' 香蕉果肉里的一排排褐色小点子就是香蕉的种子，用它能繁殖香蕉吗？ ', '不能', '能', '你告诉我', 'A');
INSERT INTO `questions` VALUES (371, ' 从人物所处的时代角度，选出不同的一项是：', '王安石', '范仲淹', '韩愈', 'C');
INSERT INTO `questions` VALUES (372, ' 纽约和法兰克福外汇市场美元对马克的汇率分别为1美元=1.5马克和1美元=1.501马克,则在纽约买进1000万美元同时在法兰克福卖出1000万美元会 ', '赚钱', '赔钱', '不赔不赚', 'A');
INSERT INTO `questions` VALUES (373, ' 东汉时，谁既是杰出的科学家又是著名的文学家？ ', '王充', '张衡', '你告诉我', 'B');
INSERT INTO `questions` VALUES (374, ' 新珍珠和老珍珠哪种价值高？ ', '新珍珠', '老珍珠', '你告诉我', 'A');
INSERT INTO `questions` VALUES (375, ' 夏天喝什么茶最去暑？ ', '冰茶', '热茶', '你告诉我', 'B');
INSERT INTO `questions` VALUES (376, ' 保险责任开始后，投保人要求解除合同的，保险人可以：', '收取全部保险费', '要求投保人支付违约金', '收取部分保险费', 'C');
INSERT INTO `questions` VALUES (377, ' 一些轿车车身后有2.0、2.6、2.8等阿拉伯数字，这是指： ', '发动机的排量', '轿车车内的豪华程度', '发动机强化程度', 'A');
INSERT INTO `questions` VALUES (378, ' 在我国设立保险公司，其注册资本的最低限额为人民币：', '2千万元', '5千万元', '2亿元', 'C');
INSERT INTO `questions` VALUES (379, ' 6岁的小明用石头把人打伤，谁来承担责任？ ', '小明', '小明的父母', '你告诉我', 'B');
INSERT INTO `questions` VALUES (380, ' 缴纳增值税的纳税人，其税务登记管理由哪负责？ ', '国税局', '地税局', '你告诉我', 'A');
INSERT INTO `questions` VALUES (381, ' \"那达慕大会”与哪个民族有关？ ', '维吾尔族', '藏族', '蒙古族', 'C');
INSERT INTO `questions` VALUES (382, ' 在荷马史诗当中，特洛伊战争持续了： ', '8年', '15年', '11年', 'C');
INSERT INTO `questions` VALUES (383, ' 中国不产狮子却有“舞狮”传统，那么中国人在兴起舞狮前舞什么？', '麒麟', '虎', '牛', 'B');
INSERT INTO `questions` VALUES (384, ' \"波尔卡\"是一种： ', '捷克民间舞蹈', '法国民间音乐', '你告诉我', 'A');
INSERT INTO `questions` VALUES (385, ' 人类食品历史上先后出现了五类食品，其中第四，五类食品是？ ', '米', '面', '酱油', 'C');
INSERT INTO `questions` VALUES (386, ' 近来被人们津津乐道的一种以长度单位为名称的技术叫做：', '忽米技术', '纳米技术', '微米技术', 'B');
INSERT INTO `questions` VALUES (387, ' 晚上看电视时，屋里的灯应该怎样？', '全部开亮', '全部关掉', '用瓦数较低的灯', 'C');
INSERT INTO `questions` VALUES (388, ' 殷墟遗址在中国的哪个古城？ ', '北京', '洛阳', '南京', 'C');
INSERT INTO `questions` VALUES (389, ' “活化石”银杏又叫“公孙树”，这是因为银杏： ', '盘根错节', '生长缓慢', '枝叶茂盛', 'B');
INSERT INTO `questions` VALUES (390, ' 我国第一大河长江有多长: ', '5480公里', '5900公里', '6300公里', 'C');
INSERT INTO `questions` VALUES (391, ' 较早使用的活字是： ', '木活字', '铅活字', '陶活字', 'C');
INSERT INTO `questions` VALUES (392, ' 人类古代的“掠夺婚”产生于哪个时期？', '母权制初期', '父权制初期', '对偶婚时期', 'B');
INSERT INTO `questions` VALUES (393, ' 银杏属于什么种类水果？ ', '仁果类', '核果类', '坚果类', 'C');
INSERT INTO `questions` VALUES (394, ' 火车司机夜间看到黄色指示灯左右摇摆意味着什么？ ', '减速', '前方有停车', '道岔开通', 'C');
INSERT INTO `questions` VALUES (395, ' 世界上流经国家最多的河是哪一条？ ', '莱茵河', '多瑙河', '雅鲁藏布江', 'B');
INSERT INTO `questions` VALUES (396, ' 蘑菇属于菌类,它是一种： ', '动物', '植物', '你告诉我', 'B');
INSERT INTO `questions` VALUES (397, ' 从抹香鲸体内提炼出的香料是：', '百里香', '沉水香', '龙涎香', 'C');
INSERT INTO `questions` VALUES (398, ' 潮汐主要是由什么引力而形成的？', '月球', '太阳', '你告诉我', 'A');
INSERT INTO `questions` VALUES (399, ' \"龟纹”在哪种工艺品中出现？ ', '刺绣', '蜡染', '扎染', 'B');
INSERT INTO `questions` VALUES (400, ' 我国名誉权规定要保护死者及其几代嫡系亲属的名誉权？ ', '一代', '二代', '三代', 'C');
INSERT INTO `questions` VALUES (401, ' 有权没收假币的是： ', '商家', '酒店', '银行', 'C');
INSERT INTO `questions` VALUES (402, ' 血液中，数量最少的是： ', '红细胞', '白细胞', '血小板', 'B');
INSERT INTO `questions` VALUES (403, ' 王利曾以汽车为张海的债务提供抵押担保，若张海不能偿还债务，且将王利的汽车变卖后，仍不足清偿，则不足部分应由谁来清偿？ ', '王利', '张海', '你告诉我', 'A');
INSERT INTO `questions` VALUES (404, ' 我们到公共图书馆看文学图书，通常应该到哪个大分类号下查找？ ', 'H', 'I', 'J', 'B');
INSERT INTO `questions` VALUES (405, ' 贫铀弹有无放射性? ', '有', '无', '你告诉我', 'A');
INSERT INTO `questions` VALUES (406, ' \"蒙太奇”原是什么术语？ ', '镜头剪接', '雕塑', '建筑学', 'C');
INSERT INTO `questions` VALUES (407, ' 下列官名中哪些不是唐朝的官名？', '尚书', '黄门', '殿中', 'C');
INSERT INTO `questions` VALUES (408, ' 宋代的\"学象生\"同现代的：', '口技', '相声', '舞狮子', 'A');
INSERT INTO `questions` VALUES (409, ' 小虾加工后的干制品通常叫做： ', '虾蛄', '沼虾', '虾米', 'C');
INSERT INTO `questions` VALUES (410, ' 汽油有不同的品种（如90号、93号等），这些数字表示的汽油标号是其 ', '甲烷值指标', '辛烷值指标', '丁烷值指标', 'B');
INSERT INTO `questions` VALUES (411, ' 古语 “待字”中，“字”的意思是指：', '字体', '墨宝', '出嫁', 'C');
INSERT INTO `questions` VALUES (412, ' 不能成为商标权主体的是： ', '企业法人', '事业法人', '自然人', 'C');
INSERT INTO `questions` VALUES (413, ' 国家在对外关系上的最高代表是： ', '国家元首', '政府首脑', '外交部长', 'A');
INSERT INTO `questions` VALUES (414, ' 郭沫若同志曾热情地赞美过什么树，并称其为“中国的国树” ', '水杉', '红豆', '银杏', 'C');
INSERT INTO `questions` VALUES (415, ' 以下电影歌曲中由外国人作曲的是： ', '《城南旧事》插曲《送别》', '《花样年华》插曲《花样的年华》', '《大话西游》主题曲《一生中最爱》', 'A');
INSERT INTO `questions` VALUES (416, ' 人民英雄纪念碑上的雕塑作品《五四运动》是: ', '浮雕', '圆雕', '你告诉我', 'A');
INSERT INTO `questions` VALUES (417, ' 干香菇怎样浸泡味更鲜？ ', '用热水浸泡', '用凉水浸泡', '你告诉我', 'A');
INSERT INTO `questions` VALUES (418, ' 小王家的水壶中积有大量水垢，长期饮用此壶中水的人 ', '易得结石症', '易得心血管疾病', '健康不受影响', 'C');
INSERT INTO `questions` VALUES (419, ' 我国第一部在国际电影节上获奖的影片是：', '《定军山》', '《渔光曲》', '《祝福》', 'B');
INSERT INTO `questions` VALUES (420, ' 亡羊补牢中的“牢”指的是： ', '牢房', '牲口圈', '院子栅栏', 'B');
INSERT INTO `questions` VALUES (421, ' 液晶是液态的晶体吗？ ', '是', '不是', '你告诉我', 'A');
INSERT INTO `questions` VALUES (422, ' 保险公司可以采取下列哪项组织形式？', '有限责任公司', '国有有限责任公司', '股份有限公司和国有独资公司', 'C');
INSERT INTO `questions` VALUES (423, ' 在我国内地驾驶车辆，必须遵守：', '右侧通行的原则', '左侧通行的原则', '中间通行的原则', 'A');
INSERT INTO `questions` VALUES (424, ' 方便面的发明者最初的愿望是： ', '战时储备', '节约时间', '在家吃面', 'C');
INSERT INTO `questions` VALUES (425, ' 世界上第一种基因移植作物是： ', '番茄', '烟草', '白菜', 'B');
INSERT INTO `questions` VALUES (426, ' 新西兰的几维鸟是曾与恐龙生活在同一时代的古老鸟类，它：', '有翅无尾', '有尾无翅', '无尾无翅', 'C');
INSERT INTO `questions` VALUES (427, ' \"打蛇打七寸”的七寸是指： ', '咽喉', '心脏', '你告诉我', 'B');
INSERT INTO `questions` VALUES (428, ' 同样重量的雪水、雨水和矿泉水，用相同的火力烧，哪种水最后开？ ', '雪水', '雨水', '矿泉水', 'A');
INSERT INTO `questions` VALUES (429, ' 显示器采用多少赫兹以上的刷新率才能基本消除屏幕闪烁对眼睛的危害？', '60 Hz', '75 Hz', '你告诉我', 'B');
INSERT INTO `questions` VALUES (430, ' 每届奥运会前夕，在奥林匹亚希腊女神赫拉庙旁，通过什么方式点燃奥运火炬？ ', '用火柴点燃', '在“永不熄灭”的火种盆里点燃', '用凹面镜聚集日光点燃', 'C');
INSERT INTO `questions` VALUES (431, ' \"高官骑瘦马”的意思是： ', '富而不显', '窝囊', '你告诉我', 'A');
INSERT INTO `questions` VALUES (432, ' 古语中的“丹书铁券”是指： ', '光辉的史册', '豪放的诗词', '免罪的凭证', 'C');
INSERT INTO `questions` VALUES (433, ' 世界上第一条地铁在1863年建于： ', '东京', '纽约', '伦敦', 'C');
INSERT INTO `questions` VALUES (434, ' 以下哪一种东西，是川菜的常用调料？ ', '孜然', '紫苏', '豆瓣', 'C');
INSERT INTO `questions` VALUES (435, ' 黄河壶口瀑布位于陕西与哪个省之间？', '宁夏', '河南', '山西', 'C');
INSERT INTO `questions` VALUES (436, ' \"锅庄”是下面哪一个少数民族的舞蹈？', '彝族', '羌族', '壮族', 'B');
INSERT INTO `questions` VALUES (437, ' 我国民间的“茶叶煮鸡蛋”对人体健康：', '有益', '无益', '你告诉我', 'B');
INSERT INTO `questions` VALUES (438, ' 负责出口产品退税管理的国家机关是：', '财政部', '国家税务局系统', '地方税务局系统', 'B');
INSERT INTO `questions` VALUES (439, ' 以下哪个不属于使馆馆长的级别？ ', '大使', '公使', '临时代办', 'C');
INSERT INTO `questions` VALUES (440, '奥林匹克运动会的发源地是: ', '古罗马', '古希腊', '古代中国', 'B');
INSERT INTO `questions` VALUES (441, '第一届奥运会什么时候开始举行?', '1890年', '1894年', '1896年', 'C');
INSERT INTO `questions` VALUES (442, '2008年奥运会将在哪个城市举行?', '巴黎', '费城', '北京', 'C');
INSERT INTO `questions` VALUES (443, '奥运会旗是:\"五色环\"旗,其中黄色环代表: ', '亚洲', '欧洲', '非洲', 'A');
INSERT INTO `questions` VALUES (444, '第一届世界杯足球赛是在哪个国家举行?', '法国', '意大利', '乌拉圭', 'C');
INSERT INTO `questions` VALUES (445, '下列国家哪个素有\"足球王国\"之称?', '德国', '意大利', '巴西', 'C');
INSERT INTO `questions` VALUES (446, '下列体育项目哪项不是奥运会\"五项全能\"之一?', '200米', '跳高', '跳远', 'B');
INSERT INTO `questions` VALUES (447, '体育运动篮球最早起源于:', '美国', '中国', '英国', 'A');
INSERT INTO `questions` VALUES (448, '女子游泳衣称\"比基尼\",这个名字源于什么名?', '设计师', '运动员', '小岛', 'C');
INSERT INTO `questions` VALUES (449, '我国第一个获得世界冠军的是誰? ', '吴传玉', '郑凤荣', '荣国团', 'C');
INSERT INTO `questions` VALUES (450, '我国最早在奥运会上夺金牌的是哪位运动员?', '李宁', '许海峰', '高凤莲', 'B');
INSERT INTO `questions` VALUES (451, '高尔夫球运动的运动场上共有多少个球洞?', '18个', '19个', '20个', 'A');
INSERT INTO `questions` VALUES (452, '围棋共有多少个棋子?', '360', '361', '362', 'B');
INSERT INTO `questions` VALUES (453, '下列中国象棋手哪位获全国冠军次数最多? ', '杨官璘', '谢思明', '胡荣华', 'C');
INSERT INTO `questions` VALUES (454, '体育项目铅球所用的球的重量约多少公斤?', '5公斤', '6公斤', '7公斤', 'C');
INSERT INTO `questions` VALUES (455, '世界游泳锦标赛最长的是男子1500米什么泳式?', '自由泳', '蛙泳', '仰泳', 'A');
INSERT INTO `questions` VALUES (456, '正式体操比赛规定男子有四项必须穿长裤,下列不属于的是:', '鞍马', '跳马', '吊环', 'B');
INSERT INTO `questions` VALUES (457, '下列哪项比赛替被队员可以在任何时候入场比赛?', '足球', '篮球', '手球', 'C');
INSERT INTO `questions` VALUES (458, '零时到八九点钟，有许多称谓，如：凌晨、黎明、清晨、早晨等，你知道凌晨是哪一段时间？', '零时至六时', '参时到六时', '天快亮时', 'A');
INSERT INTO `questions` VALUES (459, '下列哪一个口号不是奥运会的口号?', '更高', '更快', '更好', 'C');
INSERT INTO `questions` VALUES (460, '名言\"生命在于运动\"是誰说的? ', '车尔尼夫斯基', '普希金', '伏尔泰', 'C');
INSERT INTO `questions` VALUES (461, '饱食后不宜做剧烈运动这是因为:', '会得阑尾', '有障消化', '导致神经衰弱', 'B');
INSERT INTO `questions` VALUES (462, '比赛时,一队白帽,另一他蓝帽,守门员红帽,这是什么比赛?', '冰球', '橄榄球', '水球', 'C');
INSERT INTO `questions` VALUES (463, '两人徙手较量,以将对方摔倒或推出界外为胜的比赛是:', '相扑', '角力', '摔跤', 'A');
INSERT INTO `questions` VALUES (464, '职业拳击运动员争夺\"世界拳王\"必须多少周岁?', '18', '20', '21', 'C');
INSERT INTO `questions` VALUES (465, '我国哪位运动员第一次获得田径比赛冠军?', '邹振华', '徐永久', '黄志红', 'B');
INSERT INTO `questions` VALUES (466, '新中国成立后,第一次参加奥运会是在哪一年?', '1952', '1956', '1980', 'A');
INSERT INTO `questions` VALUES (467, '体操比赛中有四个动作以我国运动员的名字命名,其中鞍马是:', '李月久', '童非', '李宁', 'B');
INSERT INTO `questions` VALUES (468, '你知道曲棍球每半场的时间是多少分钟吗?', '35', '40', '45', 'B');
INSERT INTO `questions` VALUES (469, '跳竹杆是我国哪个少数民族的传统体育运动? ', '壮族', '苗族', '黎族', 'C');
INSERT INTO `questions` VALUES (470, '朱建华夺取世界跳高冠军是以什么姿式?', '跨越式', '俯卧式', '背越式', 'C');
INSERT INTO `questions` VALUES (471, '我国最早打破举重世界纪录的是哪位运动员?', '陈镜开', '陈伟强', '何灼强', 'A');
INSERT INTO `questions` VALUES (472, '周恩来倡导中小学生每天必须多长时间的体育运动?', '半小时', '一小时', '一小时半', 'B');
INSERT INTO `questions` VALUES (473, '下列哪位武术家是迷踪拳的创始人?', '董海川', '张长兴', '霍元甲', 'C');
INSERT INTO `questions` VALUES (474, '电影《神行太保》是描写哪项体育活动的故事片?', '长跑', '滑冰', '自行车', 'C');
INSERT INTO `questions` VALUES (475, '1990年第十一届亚运会在哪个城市举行?', '东京', '汉城', '北京', 'C');
INSERT INTO `questions` VALUES (476, '\"发展体育运动,增强人民体质\"是我国哪位领导人的题词?', '毛泽东', '周恩来', '邓小平', 'A');
INSERT INTO `questions` VALUES (477, '下列哪个国家因\"卒可攻王,攻后\"而禁止下国际象棋?', '印度', '印尼', '沙特阿拉伯', 'C');
INSERT INTO `questions` VALUES (478, '我国被称为哪一类体育运动的体育王国?', '羽毛球王国', '乒乓球王国', '排球王国', 'B');
INSERT INTO `questions` VALUES (479, '蓝球队员的号码因跟裁判的手势有关而没有哪三个号码?', '1 2 3', '1 2 4', '1 2 5', 'A');
INSERT INTO `questions` VALUES (480, '我国境内最早的人类是:', '北京人', '元谋人', '山顶洞人', 'B');
INSERT INTO `questions` VALUES (481, '清朝晚期,被今人誉为\"开眼看世界第一人\"的是谁?', '魏源', '龚自珍', '林则徐', 'C');
INSERT INTO `questions` VALUES (482, '红军长征中,哪次战役最突出反映毛泽东军事思想和指挥才能?', '四渡赤水', '抢渡大渡河', '飞夺沪定桥', 'A');
INSERT INTO `questions` VALUES (483, '下列哪个国家不是联合国常任理事国之一?', '英国', '法国', '德国', 'C');
INSERT INTO `questions` VALUES (484, '秦时,人们开凿沟通湘江和漓江的运河是: ', '秦渠', '灵渠', '唐徕渠', 'B');
INSERT INTO `questions` VALUES (485, '著名的亚欧间的海峡是: ', '马六甲海峡', '土耳其海峡', '直布罗陀海峡', 'B');
INSERT INTO `questions` VALUES (486, '世界上最长的运河是哪一条? ', '中国京杭大运河', '苏伊士运河', '巴拿马运河', 'A');
INSERT INTO `questions` VALUES (487, '咖啡的故乡是哪里?', '亚洲', '美洲', '非洲', 'C');
INSERT INTO `questions` VALUES (488, '我国第一个南极考察基地\"长城站\"什么时候落成? ', '1980.2', '1981.2', '1985.2', 'C');
INSERT INTO `questions` VALUES (489, '唐代诗人有称“诗圣”的杜甫“诗仙”的李白等，你可知道被人颂称“诗魔”的是谁？', '白居易', '王维', '刘禹锡', 'A');
INSERT INTO `questions` VALUES (490, '色盲患者最普遍的不易分辨的颜色是什么? ', '红绿', '蓝绿', '红蓝', 'A');
INSERT INTO `questions` VALUES (491, '下列哪种症状没有理由是遗传的? ', '精神分裂症', '近视', '口吃', 'C');
INSERT INTO `questions` VALUES (492, '世界上面值最高的邮票是匈牙利五百亿彭哥,它的图案是:', '猫', '飞鸽', '海鸥', 'B');
INSERT INTO `questions` VALUES (493, '我国少数民族分布最多的省份是: ', '广西', '西藏', '云南', 'C');
INSERT INTO `questions` VALUES (494, '泼水节是我国哪个少数民族的传统节日? ', '彝族', '回族', '傣族', 'C');
INSERT INTO `questions` VALUES (495, '下列哪一位著名画家擅长画虎?', '张大千', '张善子', '徐悲鸿', 'B');
INSERT INTO `questions` VALUES (496, '被称为\"画圣\"的古代画家是:', '吴道子', '顾恺之', '韩干', 'A');
INSERT INTO `questions` VALUES (497, '天下第一书\"《兰亭集序》是哪一位古代书法家的杰作? ', '张旭', '王献之', '王羲之', 'C');
INSERT INTO `questions` VALUES (498, '我国第一部有声影片是:', '《四郎探母》', '《定军山》', '《林则徐》', 'A');
INSERT INTO `questions` VALUES (499, '奔驰汽车原产于哪一个国家? ', '美国', '日本', '德国', 'C');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
